using Microsoft.CodeAnalysis;
using XMLDocNormalizer.Checks.Infrastructure.Exception.Flow;
using XMLDocNormalizer.Models;
using XMLDocNormalizerTests.Helpers;

namespace XMLDocNormalizerTests.Check.Semantic.Exception
{
    /// <summary>
    /// Tests runtime-target expansion for synchronous and asynchronous
    /// disposal calls generated by using constructs.
    /// </summary>
    public sealed class ExceptionFlowSummaryGraphDisposalDispatchTests
    {
        /// <summary>
        /// Ensures that synchronous disposal through a concrete base type
        /// includes the base implementation and every compatible override.
        /// </summary>
        [Fact]
        public void VirtualDispose_CreatesBaseAndOverrideEdges()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(BaseResource resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public virtual void Dispose()
                    {
                        throw new ArgumentException();
                    }
                }

                public sealed class DerivedResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge[] edges =
                GetDisposalEdges(run);

            Assert.Equal(
                2,
                edges.Length);

            AssertTargetException(
                run,
                GetEdgeForContainingType(
                    edges,
                    "BaseResource"),
                "ArgumentException");

            AssertTargetException(
                run,
                GetEdgeForContainingType(
                    edges,
                    "DerivedResource"),
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that an abstract disposal declaration is not emitted as a
        /// runtime target.
        /// </summary>
        [Fact]
        public void AbstractDispose_ExcludesAbstractTarget()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(BaseResource resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public abstract class BaseResource : IDisposable
                {
                    public abstract void Dispose();
                }

                public sealed class DerivedResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            Assert.Equal(
                "DerivedResource",
                GetTargetMethod(edge).ContainingType.Name);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that the static resource type excludes base and sibling
        /// implementations that cannot receive the runtime value.
        /// </summary>
        [Fact]
        public void DerivedStaticResourceType_ExcludesIncompatibleTargets()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(DerivedResource resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public virtual void Dispose()
                    {
                        throw new ArgumentException();
                    }
                }

                public class DerivedResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }

                public sealed class MoreDerivedResource : DerivedResource
                {
                    public override void Dispose()
                    {
                        throw new FormatException();
                    }
                }

                public sealed class SiblingResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new NotSupportedException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            string[] targetTypeNames =
                GetDisposalEdges(run)
                    .Select(
                        static edge =>
                            GetTargetMethod(edge)
                                .ContainingType.Name)
                    .OrderBy(
                        static name =>
                            name,
                        StringComparer.Ordinal)
                    .ToArray();

            Assert.Equal(
                new[]
                {
                    "DerivedResource",
                    "MoreDerivedResource"
                },
                targetTypeNames);
        }

        /// <summary>
        /// Ensures that a direct object creation fixes the runtime receiver to
        /// the created type even when the resource variable has a base type.
        /// </summary>
        [Fact]
        public void ExactObjectCreationResource_UsesCreatedType()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M()
                    {
                        using (
                            BaseResource resource =
                                new DerivedResource())
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public virtual void Dispose()
                    {
                        throw new ArgumentException();
                    }
                }

                public class DerivedResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }

                public sealed class MoreDerivedResource : DerivedResource
                {
                    public override void Dispose()
                    {
                        throw new FormatException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            Assert.Equal(
                "DerivedResource",
                GetTargetMethod(edge).ContainingType.Name);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that multiple concrete receiver types inheriting one
        /// disposal implementation create one target edge.
        /// </summary>
        [Fact]
        public void InheritedDisposeImplementation_IsDeduplicated()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(BaseResource resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public virtual void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }

                public sealed class DerivedResource : BaseResource
                {
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            Assert.Equal(
                "BaseResource",
                GetTargetMethod(edge).ContainingType.Name);
        }

        /// <summary>
        /// Ensures that an explicit IDisposable implementation becomes the
        /// runtime target of synchronous interface-based disposal.
        /// </summary>
        [Fact]
        public void IDisposableResource_UsesExplicitImplementation()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(IDisposable resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public sealed class Resource : IDisposable
                {
                    void IDisposable.Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            IMethodSymbol targetMethod =
                GetTargetMethod(edge);

            Assert.Equal(
                "Resource",
                targetMethod.ContainingType.Name);

            Assert.Single(
                targetMethod.ExplicitInterfaceImplementations);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that a derived type which reimplements IDisposable can use
        /// a different interface slot target from its base type.
        /// </summary>
        [Fact]
        public void IDisposableReimplementation_CreatesDerivedTarget()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(BaseResource resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public void Dispose()
                    {
                        throw new ArgumentException();
                    }
                }

                public sealed class DerivedResource :
                    BaseResource,
                    IDisposable
                {
                    void IDisposable.Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge[] edges =
                GetDisposalEdges(run);

            Assert.Equal(
                2,
                edges.Length);

            AssertTargetException(
                run,
                GetEdgeForContainingType(
                    edges,
                    "BaseResource"),
                "ArgumentException");

            ExceptionFlowSummaryCallEdge derivedEdge =
                GetEdgeForContainingType(
                    edges,
                    "DerivedResource");

            Assert.Single(
                GetTargetMethod(derivedEdge)
                    .ExplicitInterfaceImplementations);

            AssertTargetException(
                run,
                derivedEdge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that an IDisposable implementation selected from metadata
        /// is mapped back to its source declaration in a referenced project.
        /// </summary>
        [Fact]
        public void CrossCompilationIDisposable_UsesSourceImplementation()
        {
            const string dependencySource =
                """
                using System;

                namespace Dependency
                {
                    public sealed class Resource : IDisposable
                    {
                        public void Dispose()
                        {
                            throw new InvalidOperationException();
                        }
                    }
                }
                """;

            const string consumerSource =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(IDisposable resource)
                    {
                        using (resource)
                        {
                        }
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphProjectTestHelper.Build(
                    dependencySource,
                    consumerSource,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            IMethodSymbol targetMethod =
                GetTargetMethod(edge);

            Assert.Equal(
                "Resource",
                targetMethod.ContainingType.Name);

            Assert.False(
                targetMethod.DeclaringSyntaxReferences.IsDefaultOrEmpty);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that asynchronous disposal includes a virtual base method
        /// and every compatible override.
        /// </summary>
        [Fact]
        public void VirtualDisposeAsync_CreatesBaseAndOverrideEdges()
        {
            const string source =
                """
                using System;
                using System.Threading.Tasks;

                public static class EntryPoint
                {
                    public static async ValueTask M(BaseResource resource)
                    {
                        await using (resource)
                        {
                        }
                    }
                }

                public class BaseResource : IAsyncDisposable
                {
                    public virtual ValueTask DisposeAsync()
                    {
                        throw new ArgumentException();
                    }
                }

                public sealed class DerivedResource : BaseResource
                {
                    public override ValueTask DisposeAsync()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge[] edges =
                GetDisposalEdges(run);

            Assert.Equal(
                2,
                edges.Length);

            AssertTargetException(
                run,
                GetEdgeForContainingType(
                    edges,
                    "BaseResource"),
                "ArgumentException");

            AssertTargetException(
                run,
                GetEdgeForContainingType(
                    edges,
                    "DerivedResource"),
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that an explicit IAsyncDisposable implementation becomes
        /// the runtime target of await-using disposal.
        /// </summary>
        [Fact]
        public void IAsyncDisposableResource_UsesExplicitImplementation()
        {
            const string source =
                """
                using System;
                using System.Threading.Tasks;

                public static class EntryPoint
                {
                    public static async ValueTask M(
                        IAsyncDisposable resource)
                    {
                        await using (resource)
                        {
                        }
                    }
                }

                public sealed class Resource : IAsyncDisposable
                {
                    ValueTask IAsyncDisposable.DisposeAsync()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            IMethodSymbol targetMethod =
                GetTargetMethod(edge);

            Assert.Single(
                targetMethod.ExplicitInterfaceImplementations);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that an asynchronous disposal implementation selected from
        /// metadata is mapped back to its source declaration.
        /// </summary>
        [Fact]
        public void CrossCompilationDisposeAsync_UsesSourceImplementation()
        {
            const string dependencySource =
                """
                using System;
                using System.Threading.Tasks;

                namespace Dependency
                {
                    public sealed class Resource : IAsyncDisposable
                    {
                        public ValueTask DisposeAsync()
                        {
                            throw new InvalidOperationException();
                        }
                    }
                }
                """;

            const string consumerSource =
                """
                using System;
                using System.Threading.Tasks;

                public static class EntryPoint
                {
                    public static async ValueTask M(
                        IAsyncDisposable resource)
                    {
                        await using (resource)
                        {
                        }
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphProjectTestHelper.Build(
                    dependencySource,
                    consumerSource,
                    "M");

            ExceptionFlowSummaryCallEdge edge =
                Assert.Single(
                    GetDisposalEdges(run));

            IMethodSymbol targetMethod =
                GetTargetMethod(edge);

            Assert.Equal(
                "Resource",
                targetMethod.ContainingType.Name);

            Assert.False(
                targetMethod.DeclaringSyntaxReferences.IsDefaultOrEmpty);

            AssertTargetException(
                run,
                edge,
                "InvalidOperationException");
        }

        /// <summary>
        /// Ensures that a typed catch filter is attached to every alternative
        /// disposal target edge.
        /// </summary>
        [Fact]
        public void TypedCatch_IsAppliedToEveryDisposalDispatchEdge()
        {
            const string source =
                """
                using System;

                public static class EntryPoint
                {
                    public static void M(BaseResource resource)
                    {
                        try
                        {
                            using (resource)
                            {
                            }
                        }
                        catch (ArgumentException)
                        {
                        }
                    }
                }

                public class BaseResource : IDisposable
                {
                    public virtual void Dispose()
                    {
                        throw new ArgumentException();
                    }
                }

                public sealed class DerivedResource : BaseResource
                {
                    public override void Dispose()
                    {
                        throw new InvalidOperationException();
                    }
                }
                """;

            ExceptionFlowSummaryGraphTestRun run =
                ExceptionFlowSummaryGraphTestHelper.Build(
                    source,
                    "M");

            INamedTypeSymbol argumentException =
                run.GetRequiredType(
                    "System.ArgumentException");

            ExceptionFlowSummaryCallEdge[] edges =
                GetDisposalEdges(run);

            Assert.Equal(
                2,
                edges.Length);

            Assert.All(
                edges,
                edge =>
                    Assert.True(
                        edge.Suppresses(
                            argumentException)));
        }

        /// <summary>
        /// Gets all synchronous and asynchronous disposal edges from the root
        /// summary.
        /// </summary>
        /// <param name="run">
        /// The completed graph test run.
        /// </param>
        /// <returns>The disposal edges in recorded order.</returns>
        private static ExceptionFlowSummaryCallEdge[] GetDisposalEdges(
            ExceptionFlowSummaryGraphTestRun run)
        {
            return run.RootSummary.CallEdges
                .Where(
                    static edge =>
                        edge.CallSiteStep.Kind is
                            ExceptionFlowPathStepKind.DisposeCall or
                            ExceptionFlowPathStepKind.DisposeAsyncCall)
                .ToArray();
        }

        /// <summary>
        /// Gets the uniquely matching disposal edge declared by one type.
        /// </summary>
        /// <param name="edges">
        /// The candidate disposal edges.
        /// </param>
        /// <param name="containingTypeName">
        /// The expected target containing-type name.
        /// </param>
        /// <returns>The matching disposal edge.</returns>
        private static ExceptionFlowSummaryCallEdge
            GetEdgeForContainingType(
                IEnumerable<ExceptionFlowSummaryCallEdge> edges,
                string containingTypeName)
        {
            return Assert.Single(
                edges.Where(
                    edge =>
                        string.Equals(
                            GetTargetMethod(edge)
                                .ContainingType.Name,
                            containingTypeName,
                            StringComparison.Ordinal)));
        }

        /// <summary>
        /// Gets the method symbol represented by one disposal edge target.
        /// </summary>
        /// <param name="edge">
        /// The disposal edge to inspect.
        /// </param>
        /// <returns>The required disposal method.</returns>
        /// <exception cref="InvalidOperationException">
        /// Thrown when the edge target is not a method symbol.
        /// </exception>
        private static IMethodSymbol GetTargetMethod(
            ExceptionFlowSummaryCallEdge edge)
        {
            return edge.Target.Symbol as IMethodSymbol ??
                   throw new InvalidOperationException(
                       "The disposal edge target was not a method.");
        }

        /// <summary>
        /// Ensures that one disposal target summary contains exactly one
        /// source with the expected exception type.
        /// </summary>
        /// <param name="run">
        /// The completed graph test run.
        /// </param>
        /// <param name="edge">
        /// The edge whose target summary should be inspected.
        /// </param>
        /// <param name="exceptionTypeName">
        /// The expected simple exception type name.
        /// </param>
        private static void AssertTargetException(
            ExceptionFlowSummaryGraphTestRun run,
            ExceptionFlowSummaryCallEdge edge,
            string exceptionTypeName)
        {
            ExceptionFlowSummary targetSummary =
                run.GetRequiredSummary(
                    edge.Target);

            ExceptionFlowSummarySource source =
                Assert.Single(
                    targetSummary.Sources);

            Assert.Equal(
                exceptionTypeName,
                source.ExceptionType.Name);
        }
    }
}
