//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSharpCommentsGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CSharpCommentsGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICSharpCommentsGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] CSharpCommentsGrammarParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] CSharpCommentsGrammarParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] CSharpCommentsGrammarParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] CSharpCommentsGrammarParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] CSharpCommentsGrammarParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] CSharpCommentsGrammarParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.line_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_comment([NotNull] CSharpCommentsGrammarParser.Line_commentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.line_comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_comment([NotNull] CSharpCommentsGrammarParser.Line_commentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.claasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClaasDefinition([NotNull] CSharpCommentsGrammarParser.ClaasDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.claasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClaasDefinition([NotNull] CSharpCommentsGrammarParser.ClaasDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] CSharpCommentsGrammarParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] CSharpCommentsGrammarParser.StartContext context);
}
