//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSharpCommentsGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CSharpCommentsGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ICSharpCommentsGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.docs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocs([NotNull] CSharpCommentsGrammarParser.DocsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.docs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocs([NotNull] CSharpCommentsGrammarParser.DocsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] CSharpCommentsGrammarParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] CSharpCommentsGrammarParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] CSharpCommentsGrammarParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] CSharpCommentsGrammarParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.exceptionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionType([NotNull] CSharpCommentsGrammarParser.ExceptionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.exceptionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionType([NotNull] CSharpCommentsGrammarParser.ExceptionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.someText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSomeText([NotNull] CSharpCommentsGrammarParser.SomeTextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.someText"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSomeText([NotNull] CSharpCommentsGrammarParser.SomeTextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.exceptionTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionTag([NotNull] CSharpCommentsGrammarParser.ExceptionTagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.exceptionTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionTag([NotNull] CSharpCommentsGrammarParser.ExceptionTagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.tagContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTagContent([NotNull] CSharpCommentsGrammarParser.TagContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.tagContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTagContent([NotNull] CSharpCommentsGrammarParser.TagContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.comments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComments([NotNull] CSharpCommentsGrammarParser.CommentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.comments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComments([NotNull] CSharpCommentsGrammarParser.CommentsContext context);
}
