//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSharpCommentsGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICSharpCommentsGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CSharpCommentsGrammarBaseListener : ICSharpCommentsGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.classLink"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassLink([NotNull] CSharpCommentsGrammarParser.ClassLinkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] CSharpCommentsGrammarParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] CSharpCommentsGrammarParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.paramref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamref([NotNull] CSharpCommentsGrammarParser.ParamrefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.summary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSummary([NotNull] CSharpCommentsGrammarParser.SummaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn([NotNull] CSharpCommentsGrammarParser.ReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComment([NotNull] CSharpCommentsGrammarParser.CommentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComment([NotNull] CSharpCommentsGrammarParser.CommentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.comments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComments([NotNull] CSharpCommentsGrammarParser.CommentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.comments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComments([NotNull] CSharpCommentsGrammarParser.CommentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.line_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_comment([NotNull] CSharpCommentsGrammarParser.Line_commentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.line_comment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_comment([NotNull] CSharpCommentsGrammarParser.Line_commentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodSignature([NotNull] CSharpCommentsGrammarParser.MethodSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodSignature([NotNull] CSharpCommentsGrammarParser.MethodSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodContent([NotNull] CSharpCommentsGrammarParser.MethodContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodContent([NotNull] CSharpCommentsGrammarParser.MethodContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] CSharpCommentsGrammarParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] CSharpCommentsGrammarParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope([NotNull] CSharpCommentsGrammarParser.ScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope([NotNull] CSharpCommentsGrammarParser.ScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.classContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassContent([NotNull] CSharpCommentsGrammarParser.ClassContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.classContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassContent([NotNull] CSharpCommentsGrammarParser.ClassContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDefinition([NotNull] CSharpCommentsGrammarParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.classDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDefinition([NotNull] CSharpCommentsGrammarParser.ClassDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.usingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingClause([NotNull] CSharpCommentsGrammarParser.UsingClauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.usingClause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingClause([NotNull] CSharpCommentsGrammarParser.UsingClauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] CSharpCommentsGrammarParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] CSharpCommentsGrammarParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSharpCommentsGrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] CSharpCommentsGrammarParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSharpCommentsGrammarParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] CSharpCommentsGrammarParser.StartContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
