"""
    Creates the nodes of the architecture. There is one architecture
    node for each namespace. The resulting architecture-node hierarchy
    is isomorphic to the namespace nesting.
"""
from typing import TYPE_CHECKING

# This is True in PyCharm, but False when you run the script
if TYPE_CHECKING:
    from setup_initial import *
    from architecture_common import *


def new_component(full_name: str, subcomponents: list[Component] = []) -> Component:
    component = Component(basename(full_name), *subcomponents)
    component_map[full_name] = component
    return component


def add_component(node: Node, subcomponents: list[Component] = []) -> Component:
    """
        Creates and returns a Component with the given subcomponents
        and adds it to the component_map (where its fullname is the key).
    """
    return new_component(fullname(code_facts, node), subcomponents)


def add_components(node: Node) -> Component:
    """
        Creates Components for all descendants of node. Returns a Component for node.
        The resulting Component is added to the component_map.
    """
    subcomponents = []
    for sub_ns in sub_namespaces(node):
        subcomponents.append(add_components(sub_ns))
    return add_component(node, subcomponents)


# Create the architecture model: turn each Namespace into a Component.
# Traverses the node hierarchy bottom up because children must be known
# when their parent is to be created.
for namespace in INPUT_RFG.nodes(code_facts, only_namespaces):
    if parent(code_facts, namespace) is None:
        ARCH.register(add_components(namespace))

# Additional Lexer component for the classes generated by AntLR, which do not
# belong to a namespace.
ARCH.SEE.Scanner.Antlr.register(new_component("SEE.Scanner.Antlr.Lexer"))

# We allow all SEE code to depend on System.
#arch.SEE.depends_on(arch.System)

# Determined via dominance tree.
#arch.SEE.UI.HelpSystem.depends_on(arch.UnityEngine.Video)
#arch.SEE.Game.Drawable.depends_on(arch.UnityEngine.TextCore)
#arch.SEE.Game.Evolution.depends_on(arch.SEE.Net.Actions.Animation)
#arch.SEE.UI.RuntimeConfigMenu.depends_on(arch.SEE.Net.Actions.RuntimeConfig)
