#if UNITY_EDITOR

using System.Collections.Generic;
using System.Linq;
using System.Xml.Linq;
using UnityEditor;

namespace SEEEditor
{
    /// <summary>
    /// Repairs the C# project files generated by Unity for Visual Studio so that they
    /// can be built outside of Unity (by Visual Studio or MSBuild).
    /// <para>
    /// If an assembly has a csc.rsp file with references such as
    /// <c>-r:System.IO.Compression.FileSystem.dll</c> (as NuGetForUnity does), the
    /// project generator adds a second reference with the same name whose hint path
    /// points to a .NET Standard compatibility shim. Unity's compiler receives both
    /// files and uses the real assembly, but MSBuild keeps only one reference per
    /// name and picks the shim, which lacks types such as <c>ZipFile</c>. This class
    /// removes such shim references whenever a non-shim reference with the same name
    /// exists.
    /// </para>
    /// <para>
    /// Moreover, the generated projects target .NET Framework 4.7.1, while some
    /// precompiled plugins (e.g., DOTween) are built against 4.7.2. Unity ignores this
    /// mismatch, but MSBuild drops such references (warning MSB3274). This class
    /// therefore tells MSBuild to ignore the mismatch, too.
    /// </para>
    /// </summary>
    internal class CSProjectReferenceFixer : AssetPostprocessor
    {
        /// <summary>
        /// The part of a hint path identifying a .NET Standard compatibility shim.
        /// </summary>
        private const string shimPathFragment = @"\NetStandard\compat\";

        /// <summary>
        /// The MSBuild property that makes MSBuild accept references built against a
        /// higher .NET Framework version than the one targeted by the project.
        /// </summary>
        private const string ignoreVersionMismatchProperty
            = "ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch";

        /// <summary>
        /// Removes duplicate references to .NET Standard compatibility shims from the
        /// generated C# project file and makes MSBuild accept references built against
        /// a higher .NET Framework version.
        /// </summary>
        /// <param name="path">The path of the generated project file.</param>
        /// <param name="content">The content of the generated project file.</param>
        /// <returns>The repaired content of the project file.</returns>
        /// <remarks>Called by the Visual Studio Editor package via reflection.</remarks>
        private static string OnGeneratedCSProject(string path, string content)
        {
            XDocument document = XDocument.Parse(content);
            XNamespace ns = document.Root.Name.Namespace;

            List<XElement> shims = new();
            foreach (IGrouping<string, XElement> group in document.Descendants(ns + "Reference")
                                                                  .GroupBy(r => (string)r.Attribute("Include")))
            {
                List<XElement> references = group.ToList();
                if (references.Count > 1 && references.Any(r => !IsShim(r, ns)))
                {
                    shims.AddRange(references.Where(r => IsShim(r, ns)));
                }
            }

            foreach (XElement shim in shims)
            {
                shim.Remove();
            }

            XElement propertyGroup = document.Root.Element(ns + "PropertyGroup");
            if (propertyGroup != null && propertyGroup.Element(ns + ignoreVersionMismatchProperty) == null)
            {
                propertyGroup.Add(new XElement(ns + ignoreVersionMismatchProperty, "true"));
            }
            return document.Declaration + "\r\n" + document;
        }

        /// <summary>
        /// Whether <paramref name="reference"/> refers to a .NET Standard compatibility shim.
        /// </summary>
        /// <param name="reference">A reference element of a project file.</param>
        /// <param name="ns">The XML namespace of the project file.</param>
        /// <returns>True if the hint path of <paramref name="reference"/> points to a shim.</returns>
        private static bool IsShim(XElement reference, XNamespace ns)
        {
            string hintPath = (string)reference.Element(ns + "HintPath");
            return hintPath != null && hintPath.Contains(shimPathFragment);
        }
    }
}

#endif
