version: "3.8"

services:

  traefik:
    image: traefik:v2.9
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"
      # Uncomment this line to enable the traefik dashboard
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    build: ./Frontend
    container_name: see-frontend
    restart: always
    depends_on:
      - backend
      - traefik
    environment:
      # Backend API URL
      VITE_APP_API_URL: http://see.localhost/api/v1/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${HOSTNAME}`) && !PathPrefix(`/api`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    networks:
      - traefik
      - default

  backend:
    privileged: true
    build: ./Backend
    container_name: see-backend
    restart: always
    depends_on:
      - traefik
    volumes:
      - backend-data:/see
      # - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ":8080"
    environment:
      BACKEND_DOMAIN: see.localhost
      FRONTEND_DOMAIN: see.localhost
      FRONTEND_SCHEME: HTTP
      FILESTORAGE_DIR: /see/file-storage
      SQLITE_DB_FILE: /see/database.db
      # Docker daemon must be reachable from backend container to spawn game servers.
      DOCKER_HOST: unix:///var/run/docker.sock
      # This is the docker host's external IP or domain. Game servers will be reachable on this host.
      DOCKER_HOST_EXTERNAL: localhost
      GAME_SERVER_IMAGE: localhost/see-gameserver:latest
      # Use a new secure random secret for production!
      #   dd if=/dev/random bs=64 count=1 | base64 -w 0
      JWT_SECRET: Pd0lrQXVI8wVYuX+LGtJRCd62gvRDfS0Gd2BnUdwFWJsHiNDf6FOx9muwOTPB7YBqt1MDMlS4emg2DvDOHSkOg==
      JWT_EXPIRATION: 86400000
      # This will add an admin account to the backend. Use with care!
      ADD_ADMIN_NAME: admin
      ADD_ADMIN_PASSWORD: admin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - traefik
      - default

networks:
  traefik:
  default:


volumes:
  backend-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./backend-data
