#!/bin/sh

# Runs all shell scripts in current directory, stopping if any script fails.
# Note that by 'shell scripts', only files with extension '.sh' is included.
# Scripts with any other filetype will not be run.

set -e

if [ -n "$CI" ]; then
    echo "Running all pre-commit hook scripts..."
fi

for file in ./GitScripts/*.sh; do
    if [ -n "$CI" ]; then
        echo "Running $file..."
    fi
    $file
done
