using UnityEngine;

namespace SEE.Layout
{
    /// <summary>
    /// A factory for visual representations of graph nodes in the scene.
    /// </summary>
    public abstract class BlockFactory
    {
        /// <summary>
        /// Creates and returns a new block representation of a graph node.
        /// </summary>
        /// <returns>new block representation</returns>
        public abstract GameObject NewBlock();

        /// <summary>
        /// The length unit of a block representation in Unity measures.
        /// </summary>
        /// <returns>length unit of a block representation in Unity measure</returns>
        public virtual float Unit()
        {
            return 1.0f;
        }

        /// <summary>
        /// Returns the size of the block generated by this factory.
        /// Precondition: The given block must have been generated by this factory.
        /// </summary>
        /// <param name="block">block whose size is to be returned</param>
        /// <returns>size of the block</returns>
        public virtual Vector3 GetSize(GameObject block)
        {
            // Nodes represented by cubes have a renderer from which we can derive the
            // extent.
            Renderer renderer = block.GetComponent<Renderer>();
            if (renderer != null)
            {
                return renderer.bounds.size;
            }
            else
            {
                Debug.LogErrorFormat("Node {0} (tag: {1}) without renderer.\n", block.name, block.tag);
                return Vector3.one;
            }
        }

        /// <summary>
        /// Scales the given block by the given scale. Note: The unit of scaling depends
        /// upon a block factory type. Subclasses may use different units. For instance,
        /// a cube factory measures in terms of Unity units, while a BuildingFactory
        /// uses floors.
        /// Precondition: The given block must have been generated by this factory.
        /// </summary>
        /// <param name="block">block to be scaled</param>
        /// <param name="scale">scaling factor</param>
        public abstract void ScaleBlock(GameObject block, Vector3 scale);

        /// <summary>
        /// Sets the position of the current block. The given x and z positions are interpreted
        /// as the center of the block and the y co-ordinate specifies the ground level of the 
        /// block.
        /// </summary>
        /// <param name="block">block to be positioned</param>
        /// <param name="position">where to position the block</param>
        public abstract void SetPosition(GameObject block, Vector3 position);

        /// <summary>
        /// Returns the center of the roof of the given block.
        /// </summary>
        /// <param name="block">block for which to determine the roof position</param>
        /// <returns>roof position</returns>
        public virtual Vector3 Roof(GameObject block)
        {
            Vector3 result = block.transform.position;
            result.y += GetSize(block).y / 2.0f;
            return result;
        }

        /// <summary>
        /// Returns the center of the ground of a block.
        /// </summary>
        /// <param name="block">block for which to determine the ground position</param>
        /// <returns>ground position</returns>
        public virtual Vector3 Ground(GameObject block)
        {
            Vector3 result = block.transform.position;
            result.y -= GetSize(block).y / 2.0f;
            return result;
        }
    }
}
