using UnityEngine;

namespace SEE.Layout
{
    /// <summary>
    /// A factory for visual representations of graph nodes in the scene.
    /// </summary>
    public abstract class NodeFactory
    {
        /// <summary>
        /// Creates and returns a new block representation of a graph node.
        /// The interpretation of the given index depends upon the subclasses.
        /// It can be used to specify a visual property of the objects such
        /// as the color. The allowed range of it depends upon the subclasses, too.
        /// </summary>
        /// <param name="index">specifies an additional visual parameter of the object</param>
        /// <returns>new block representation</returns>
        public abstract GameObject NewBlock(int index = 0);

        /// <summary>
        /// The collection of materials to be used by this node factory.
        /// </summary>
        protected Materials materials;

        /// <summary>
        /// The number of materials offered.
        /// </summary>
        /// <returns>number of materials offered</returns>
        public virtual int NumberOfMaterials()
        {
            return materials.NumberOfMaterials();
        }

        /// <summary>
        /// The length unit of a block representation in Unity measures.
        /// </summary>
        [SerializeField]
        public float Unit
        {
            get => unit;
            set => unit = value;
        }

        /// <summary>
        /// The length unit of a block representation in Unity measures.
        /// </summary>
        protected float unit = 1.0f;

        /// <summary>
        /// Returns the size of the block generated by this factory in Unity units.
        /// Precondition: The given block must have been generated by this factory.
        /// </summary>
        /// <param name="block">block whose size is to be returned</param>
        /// <returns>size of the block</returns>
        public virtual Vector3 GetSize(GameObject block)
        {
            // Nodes represented by cubes have a renderer from which we can derive the
            // extent.
            Renderer renderer = block.GetComponent<Renderer>();
            if (renderer != null)
            {
                return renderer.bounds.size;
            }
            else
            {
                Debug.LogErrorFormat("Node {0} (tag: {1}) without renderer.\n", block.name, block.tag);
                return Vector3.one;
            }
        }

        /// <summary>
        /// Sets the size (its scale) of the given block by the given size. Note: The unit of 
        /// size is Unity units.
        /// Precondition: The given block must have been generated by this factory.
        /// </summary>
        /// <param name="block">block to be scaled</param>
        /// <param name="size">new size</param>
        public virtual void SetSize(GameObject block, Vector3 size)
        {
            block.transform.localScale = size;
        }

        /// <summary>
        /// Sets the width of the object (x axis) to the given value in Unity units.
        /// </summary>
        /// <param name="block">block to be adjusted</param>
        /// <param name="value">new value for width</param>
        public virtual void SetWidth(GameObject block, float value)
        {
            block.transform.localScale = new Vector3(value, block.transform.localScale.y, block.transform.localScale.z);
        }

        /// <summary>
        /// Sets the height of the object (y axis) to the given value in Unity units.
        /// </summary>
        /// <param name="block">block to be adjusted</param>
        /// <param name="value">new value for height</param>
        public virtual void SetHeight(GameObject block, float value)
        {
            block.transform.localScale = new Vector3(block.transform.localScale.x, value, block.transform.localScale.z);
        }

        /// <summary>
        /// Sets the depth of the object (y axis) to the given value in Unity units.
        /// </summary>
        /// <param name="block">block to be adjusted</param>
        /// <param name="value">new value for depth</param>
        public virtual void SetDepth(GameObject block, float value)
        {
            block.transform.localScale = new Vector3(block.transform.localScale.x, block.transform.localScale.y, value);
        }

        /// <summary>
        /// Sets the position of the current block. The given position is
        /// interpreted as the center (x,z) of the block on the ground (y).
        /// </summary>
        /// <param name="block">block to be positioned</param>
        /// <param name="position">where to position the block (its center) on the ground y</param>
        public virtual void SetGroundPosition(GameObject block, Vector3 position)
        {
            Vector3 extent = GetSize(block) / 2.0f;
            block.transform.position = new Vector3(position.x, position.y + extent.y, position.z);
        }

        /// <summary>
        /// Sets the local position of the current block within its parent object.
        /// The given position is interpreted as the center (x,z) of the block on the ground (y).
        /// </summary>
        /// <param name="block">block to be positioned</param>
        /// <param name="position">where to position the block (its center)</param>
        public virtual void SetLocalGroundPosition(GameObject block, Vector3 position)
        {
            Vector3 extent = GetSize(block) / 2.0f;
            block.transform.localPosition = new Vector3(position.x, position.y + extent.y, position.z);
        }

        /// <summary>
        /// Returns the center of the roof of the given block.
        /// </summary>
        /// <param name="block">block for which to determine the roof position</param>
        /// <returns>roof position</returns>
        public virtual Vector3 Roof(GameObject block)
        {
            Vector3 result = block.transform.position;
            result.y += GetSize(block).y / 2.0f;
            return result;
        }

        /// <summary>
        /// Returns the center of the ground of a block.
        /// </summary>
        /// <param name="block">block for which to determine the ground position</param>
        /// <returns>ground position</returns>
        public virtual Vector3 Ground(GameObject block)
        {
            Vector3 result = block.transform.position;
            result.y -= GetSize(block).y / 2.0f;
            return result;
        }

        /// <summary>
        /// The center position of the block.
        /// </summary>
        /// <param name="block">block for which to retrieve the center position</param>
        /// <returns>center position of the block</returns>
        public virtual Vector3 GetCenterPosition(GameObject block)
        {
            // The center position in Unity is normally its transform.position
            // (as opposed to CScape buildings).
            return block.transform.position;
        }
    }
}
