//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Single Throttle
        {
            get
            {
                return SteamVR_Actions.default_Throttle;
            }
        }
        
        public virtual SteamVR_Action_Single Grab
        {
            get
            {
                return SteamVR_Actions.default_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.default_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean Cancel
        {
            get
            {
                return SteamVR_Actions.default_Cancel;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.default_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Home
        {
            get
            {
                return SteamVR_Actions.default_Home;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Zoom
        {
            get
            {
                return SteamVR_Actions.default_Zoom;
            }
        }
        
        public virtual SteamVR_Action_Boolean ResetCharts
        {
            get
            {
                return SteamVR_Actions.default_ResetCharts;
            }
        }
        
        public virtual SteamVR_Action_Boolean CreateChart
        {
            get
            {
                return SteamVR_Actions.default_CreateChart;
            }
        }
        
        public virtual SteamVR_Action_Boolean LGrip
        {
            get
            {
                return SteamVR_Actions.default_LGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean RGrip
        {
            get
            {
                return SteamVR_Actions.default_RGrip;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenSettingsMenu
        {
            get
            {
                return SteamVR_Actions.default_OpenSettingsMenu;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
